name: 自動分析ワークフロー

on:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  check-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得

      - name: 実行時刻の設定
        id: datetime
        run: echo "now=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: データ更新の確認
        id: check_updates
        run: |
          source scripts/update_analysis.sh
          if [ $? -eq 0 ]; then
            echo "更新なし"
            exit 0
          fi

      - name: Slack通知（更新なし）
        if: steps.check_updates.outcome == 'success' && steps.check_updates.conclusion == 'success'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "データ更新チェック完了",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*データ更新チェック完了*\n- 実行時刻: ${{ steps.datetime.outputs.now }}\n- 結果: 新しいデータの更新はありません"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Slack通知（更新あり）
        if: steps.check_updates.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "データ更新検出",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*新しいデータの更新を検出*\n- 実行時刻: ${{ steps.datetime.outputs.now }}\n- 結果: 新しいデータの更新があります"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Slack通知（エラー）
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "ワークフロー実行エラー",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*ワークフロー実行中にエラーが発生*\n- 実行時刻: ${{ steps.datetime.outputs.now }}\n- 詳細: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 